backend:
  name: git-gateway
  branch: main
  identity_url: "https://gameforge-games.netlify.app/.netlify/identity"
  gateway_url: "https://gameforge-games.netlify.app/.netlify/git"
media_folder: "images"
public_folder: "images"
collections:
  - name: "database"
    label: "Game & Movie Database"
    files:
      - label: "Database File"
        name: "games"
        file: "games.json"
        fields:
          - label: "Games List"
            name: "games_list"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "select", options: ["Action", "RPG", "Racing", "Horror"]}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "System Requirements (Separate by |)", name: "req", widget: "string"}
              - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
              - {label: "Gallery Images", name: "gallery", widget: "list", field: {label: "Image", name: "img", widget: "image"}}
              - {label: "Torrent Link", name: "torrent", widget: "string"}
          - label: "Movies List"
            name: "movies_list"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "select", options: ["Action", "Sci-Fi", "Comedy", "Horror", "Thriller"]}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Main Actors (Separate by |)", name: "actors", widget: "string"}
              - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
              - {label: "Gallery Images", name: "gallery", widget: "list", field: {label: "Image", name: "img", widget: "image"}}
              - {label: "Download Link", name: "torrent", widget: "string"}
